# This file is a template, and might need editing before it works on your project.
image: node:latest

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
    paths:
        - node_modules/

dev-pages:
    script:
        - yarn install
        - ./node_modules/.bin/gatsby build
    artifacts:
        paths:
            - public
    only:
        - master
